### ISSUE TITLE
[BUG] faild to build

### ISSUE THREAD

**Issue by gomma91** [Da4ndo/Hyde-Ext#1]
Hi, today while I was updating the hyde-ext package to 1.3.1-1, this error appeared, how can I resolve it? Thanks for the help. PS I also tried to build it manually, download it again, clear the cache, but I always get the same result

![240928_15h34m45s_screenshot](https://github.com/user-attachments/assets/bea3ba1c-d04b-418e-acd3-5a03c411fa6d)

**Comment by Da4ndo** [comment]
Sorry, I was still testing the github action that automatically publishes to AUR after release. The directory name to cd into in makepkg was incorrect. **I fixed it.** 

I apologize for the inconvenience. Check out the latest version 1.3.3. Also, please let me know in Discussions what features you would want to see.

**Comment by gomma91** [comment]
Hi, thanks for the fix, it worked. 

A theme editor tools would be interesting as a feature also to create new ones, 
...I tried to create new ones, but with poor results :'(.
